### ISSUE TITLE
Aladin map position

### ISSUE THREAD

**Issue by pruzhinskaya** [hombit/ztf-viewer#10]
Let's discuss the position of the Aladin map. It would be nice to have closer to the light curve... And it is possible to load automatically PanStarrs map not sdss or dss?

<img width="647" alt="изображение" src="https://user-images.githubusercontent.com/16917953/86919268-a344af80-c130-11ea-87d2-db933d35c05e.png">

**Comment by hombit** [comment]
You could need to flush your JS cache to see Panstarrs
